cmake_minimum_required(VERSION 3.18)
project(mathicgb-consumer LANGUAGES CXX)
find_package(mathicgb 1.4 CONFIG REQUIRED)
add_executable(consumer consumer.cpp)
target_link_libraries(consumer PRIVATE mathicgb::mathicgb)
if(EXPECT_DEBUG)
  target_compile_definitions(consumer PRIVATE EXPECT_DEBUG)
endif()
if(EXPECT_NO_TBB)
  target_compile_definitions(consumer PRIVATE EXPECT_NO_TBB)
endif()
enable_testing()
add_test(NAME installed-consumer COMMAND consumer)
