.TH MGB "1" "April 2015"
.SH NAME
Mathicgb: \- Compute (signature) Groebner bases using the fast data\%structures
from mathic.
.SH DESCRIPTION
.HP
gb \- Compute a Groebner basis.
.HP
help \- Return information about the command line interface.
.HP
matrix \- Perform matrix computations.
.HP
siggb \- Compute a signature Groebner basis
.SH AUTHORS
Mathicgb was written by Bjarke Hammersholt Roune <bjarke.roune@gmail.com> and
Michael Stillman <mike@math.cornell.edu>. This manual page was written by Doug
Torrance <dtorrance@piedmont.edu> for the Debian project (but may be
used by others).
